- name: create webserver
  hosts: web
  remote_user: ec2-user
  become: yes
  gather_facts: False
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: yes
    - name: copy contents
      copy:
        src: scriptfile
        dest: /var/www/html/index.html
        mode: '777'
