- name: creation of ec2
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: create ec2
      ec2:
        image: ami-079b5e5b3971bd10d
        instance_type: t2.micro
        key_name: Mumbaikey
        region: ap-south-1
        vpc_subnet_id: subnet-07750bb272328afec
        group: default
        count: 1
        assign_public_ip: yes
        wait: yes
        instance_tags:
          name: webserver1
